name: wxread

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行 (北京时间早上 8 点)
  workflow_dispatch:  # 手动触发

jobs:
  random_delay:
    runs-on: ubuntu-22.04
    outputs:
      delay: ${{ steps.calculate_delay.outputs.seconds }} # 修改为使用 calculate_delay 步骤的输出
    steps:
      - name: Calculate Delay
        id: calculate_delay
        run: |
          MAX_DELAY=$((86400 - 18000)) # 最大的延迟时间 = 24 小时 - 5 小时 = 19 小时 (秒)
          RANDOM_SECONDS=$((RANDOM % MAX_DELAY)) # 生成 0 到 MAX_DELAY 之间的随机秒数
          echo "seconds=$RANDOM_SECONDS" >> $GITHUB_OUTPUT

  deploy:
    needs: random_delay
    runs-on: ubuntu-22.04
    environment: AutoRead  # 指定环境
    steps:
      - name: Sleep
        run: sleep ${{ needs.random_delay.outputs.delay }}
        shell: bash

      - name: Set DNS to Google's DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install certifi==2024.8.30 charset-normalizer==3.4.0 idna==3.10 requests==2.32.3 urllib3==2.2.3

      - name: Run deployment script
        env:
          WXREAD_CURL_BASH: ${{ secrets.WXREAD_CURL_BASH }}
          PUSH_METHOD: ${{ secrets.PUSH_METHOD }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          WXPUSHER_SPT: ${{ secrets.WXPUSHER_SPT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          READ_NUM: ${{ vars.READ_NUM }}  # 使用 Repository Variables

        run: |
          python main.py
